version: "3.8"

services:
  nocturne:
    build: .
    container_name: nocturne_container
    restart: always
    privileged: true
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/snd:/dev/snd"
    environment:
      DISPLAY: $DISPLAY
      PULSE_SERVER: unix:/run/user/1000/pulse/native
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse:/run/user/1000/pulse
    working_dir: /app
    command: ["python", "main.py"]